stages:
  - Test
  - Publish

Test:
  stage: Test
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  services:
    - name: docker:19.03.12-dind
      alias: docker
  script:
    - docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from lippia
  artifacts:
    when: always
    paths:
      - target/reports/

GitHub publish:
  image: crowdar/pipeline:2.0.1
  stage: Publish
  script:
    - git remote add github https://$GITHUB_USER:$GITHUB_TOKEN@github.com/Crowdar/Lippia-Low-Code-Sample-Project.git
    - git push -u github HEAD:main
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
