image: docker:latest

services:
  - name: docker:24.0.0-rc.1-dind-alpine3.17

Test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from lippia
  artifacts:
    when: always
    paths:
      - target/reports/
