image: docker:latest
services:
  - name: docker:24.0.0-rc.1-dind-alpine3.17
    alias: docker
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''

Test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from lippia
  artifacts:
    when: always
    paths:
      - target/reports/
